# Introducción a NumPy

Este Práctico proporciona una introducción básica a NumPy, destacando algunas de sus características clave y mostrando ejemplos de su uso. A continuación tendrán un resúmen de algunos comando y su implementación. Esto servirá de guia para desarrollar las actividades propuestas a continuación.

# Comparación entre uso de vectores de Python y NumPy

A continuación se presentan varios aspectos para poder comparar la implementación de vectores a través del tipo de datos LISTA , comparado con la implementación de vectores con NumPy:

#### 1- Creación de vectores

En esta celda, se importa la biblioteca NumPy y se CREA UN VECTOR utilizando Python puro y NumPy. Luego, se imprime cada uno de los vectores.

In [24]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [25]:
import numpy as np

vector_py = [1, 2, 3, 4, 5]
vector_np = np.array([1, 2, 3.5, 4, 5])
print("Vector en Python puro:", vector_py)
print("Vector en NumPy:", vector_np)

Vector en Python puro: [1, 2, 3, 4, 5]
Vector en NumPy: [1.  2.  3.5 4.  5. ]


#### 2- Operaciones matemáticas

En esta celda, se realizan operaciones matemáticas en un vector utilizando Python puro y NumPy. Luego, se imprime el resultado de cada operación.

In [26]:
vector_py = [1, 2, 3, 4, 5]
vector_np = np.array([1, 2, 3, 4, 5])
suma_py = [x + 2 for x in vector_py]
suma_np = vector_np *2
#print("Suma en Python puro:", suma_py)
#print("Suma en NumPy:", suma_np)
vector_py*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

#### 3- Indexado y segmentación

En esta celda, se realiza el indexado y segmentación en un vector utilizando Python puro y NumPy. Luego, se imprime el resultado de cada operación.

In [27]:
vector_py = [1, 2, 3, 4, 5]
vector_np = np.array([1, 2, 3, 4, 5])
segmento_py = vector_py[1:4]
segmento_np = vector_np[1:4]
print("Segmento en Python puro:", segmento_py)
print("Segmento en NumPy:", segmento_np)

Segmento en Python puro: [2, 3, 4]
Segmento en NumPy: [2 3 4]


## Operaciones entre vectores y funciones sobre vectores

A continuación se presentan algunos ejemplos de operaciones básicas entre vectores utilizando NumPy:

#### Suma de vectores

En esta celda, se crea un vector 'vector_a' y un vector 'vector_b', y se realiza la suma de ambos vectores utilizando NumPy. Luego, se imprime el resultado.

In [28]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
suma_vector = vector_a + vector_b
print("Suma de vectores:", suma_vector)

Suma de vectores: [5 7 9]


# ***EJERCICIOS PARTE 1***
***EJERCICIO 1:***

Dada la siguiente tabla (matriz) de datos, donde cada fila representa la cantidad que se vendio en referencia a un solo producto durante toda la semana; mientras que cada columna representa la venta total en un dia de la semana.Obtener la siguiente información detallada:

* Importe total de la venta por cada dia de la semana
* Importe total de la venta por cada producto en la semana
* Importe total de la venta en toda la semana

In [29]:
import numpy as np


# Datos de ventas diarias de 4 productos durante una semana

ventas_diarias = np.array(
    #Lun,Mar,Mie,Jue,Vie,Sab,Dom
    [[20, 15, 25, 30, 18, 22, 24],  #Producto A
    [12, 20, 14, 8, 15, 18, 16],    #Producto B
    [35, 28, 32, 30, 26, 24, 30],   #Producto C
    [40, 38, 45, 42, 39, 41, 37]    #Producto D
    ]
)

print("Matriz de ventas diarias:",ventas_diarias)

#==== FORMAS DE RECORRER UNA MATRIZ FIJADA LA COLUMNA J=1
#    Calcula la suma total del dia lunes
suma=0
for i in range(4):
  print(ventas_diarias[i,1])
  suma=suma+ventas_diarias[i,1]
print('la suma total del lunes es:', suma)

#===== IMPLEMENTACIÓN DE UN MÉTODO DE NUMPY
# Sumar las ventas por día (sumar las columnas)
ventas_por_dia = np.sum(ventas_diarias, axis=0)
print("Importe total de la venta por día de la semana:",ventas_por_dia)

# b) Importe total de la venta por cada producto en la semana
importe_por_producto = np.sum(ventas_diarias, axis=1)
print("\nImporte total de la venta por producto en la semana:")
print(importe_por_producto)

# c) Importe total de la venta en toda la semana
importe_total_semana = np.sum(ventas_diarias)
print("\nImporte total de la venta en toda la semana:", importe_total_semana)

Matriz de ventas diarias: [[20 15 25 30 18 22 24]
 [12 20 14  8 15 18 16]
 [35 28 32 30 26 24 30]
 [40 38 45 42 39 41 37]]
15
20
28
38
la suma total del lunes es: 101
Importe total de la venta por día de la semana: [107 101 116 110  98 105 107]

Importe total de la venta por producto en la semana:
[154 103 205 282]

Importe total de la venta en toda la semana: 744


**EJERCICIO 2:**

Crear un programa donde se le pida al usuario que ingrese la cantidad de elementos de una lista de números reales positivos. Luego Convertir esa lista en un vector de Numpy.

In [30]:
cantidad = int(input("Ingrese la cantidad de elementos de la lista: "))
while (cantidad <= 0):
    print("Ingrese un número positivo mayor que cero.")
    cantidad = int(input("Ingrese la cantidad de elementos de la lista: "))
lista = []
for i in range(cantidad):
    numero = float(input(f"Ingrese el número {i + 1}: "))
    if numero < 0:
        print("Ingrese un número real positivo.")
    else:
         lista.append(numero)
vector = np.array(lista)
print("Lista ingresada:", lista)
print("Vector NumPy:", vector)


ValueError: invalid literal for int() with base 10: ''

**Ejercicio 3:**

Crear un programa donde el usuario ingrese la cantidad de filas y columnas que tendra una tabla de datos. Luego el programa pedira ingresar los datos de la tabla fila por fila. Todos los datos serán numéricos.

Mostrar la tabla ingresada en formato LISTA de Python, y mostrar la misma tabla en formato array de Numpy.

Solicitar al usuario que ingrese las posiciones de dos filas y realice la suma de las mismas. Mostrar este vector resultado.

In [ ]:
# Obtener el número de filas y columnas de la tabla
num_filas = int(input("Ingrese la cantidad de filas: "))
num_columnas = int(input("Ingrese la cantidad de columnas: "))

# Inicializar la tabla como una lista de listas
tabla = []
for _ in range(num_filas):
    fila = []
    for _ in range(num_columnas):
        valor = float(input("Ingrese un valor numérico: "))
        fila.append(valor)
    tabla.append(fila)

# Mostrar la tabla en formato de lista de Python
print("Tabla en formato de lista de Python:")
for fila in tabla:
    print(fila)

# Crear un array de NumPy a partir de la tabla
tabla_np = np.array(tabla)

# Mostrar la tabla en formato de array de NumPy
print("Tabla en formato de array de NumPy:")
print(tabla_np)

# Solicitar las posiciones de las filas para la suma
fila1 = int(input("Ingrese la posición de la primera fila: "))
fila2 = int(input("Ingrese la posición de la segunda fila: "))

# Realizar la suma de las filas y mostrar el vector resultado
print (f"sumamos {tabla_np[fila1]} + {tabla_np[fila2]}")
suma_filas = tabla_np[fila1] + tabla_np[fila2]
print(f"Resultado de la suma de las filas: {suma_filas}")

Tabla en formato de lista de Python:
[1.0, 2.0, 3.0]
[4.0, 5.0, 6.0]
[7.0, 8.0, 9.0]
Tabla en formato de array de NumPy:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
sumamos [1. 2. 3.] + [4. 5. 6.]
Resultado de la suma de las filas: [5. 7. 9.]


**Ejercicio 4:**

A continuación se muestran los valores de los siguientes productos:

['arroz', 'harina','fideo','yerba','azucar']=[145.6 , 100 , 89.90 , 700 , 95]

Los valores de estos productos son aproximados de hace dos meses, debido a la inflación y alza de los precios, se vieron afectados de la siguiente manera:

* Producto arroz , harina, azucar duplicaron su precio
* Productos restantes incrementaron en un 75% su precio

Mostrar los datos en forma de vector y actualizar sus precios, de manera que se pueda comparar ambos vectores.

In [ ]:
# Definir los productos y sus valores iniciales
productos = ['arroz', 'harina', 'fideo', 'yerba', 'azucar']
valores_iniciales = np.array([145.6, 100, 89.90, 700, 95])

# Aplicar modificaciones a los valores
valores_actualizados = np.copy(valores_iniciales)
valores_actualizados[0:3] *= 2  # Duplicar el precio de arroz, harina y azucar
valores_actualizados[3:] *= 1.75  # Incrementar en un 75% el precio de los otros productos

# Mostrar los datos en forma de vectores
print("Valores Iniciales:")
print(valores_iniciales)

print("\nValores Actualizados:")
print(valores_actualizados)

Valores Iniciales:
[145.6 100.   89.9 700.   95. ]

Valores Actualizados:
[ 291.2   200.    179.8  1225.    166.25]


***EJERCICIO 5***

Completar la siguiente tabla de comandos y funciones que se utilizarán sobre vectores definidos a través de Numpy

|    | Comando | operación y funcionalidad |resultado | ejemplo |
|---|    ---   |               ---         |    ---   |    ---  |
1   | np.array([lista])|     crea un vector o table con Numpy  |  matriz   |np.array([1.6, 2, 0, 6.75])
2   |np.sqrt(vector)|       Calcula la raíz cuadrada de cada elemento en el vector utilizando la biblioteca Numpy   |   Vector NumPy con las raíces cuadradas de los elementos originales |  np.sqrt(vector_np)
3   |np.random.rand(n)|     Genera un vector de longitud 'n' con valores aleatorios en el rango [0, 1) utilizando la biblioteca Numpy   |   Vector NumPy con valores aleatorios en el intervalo [0, 1). | np.random.rand(5)
4   |np.ones((n))|          Crea una matriz de forma '(n)' con todos los elementos iguales a 1 utilizando la biblioteca Numpy   |  Matriz NumPy con todos los elementos iguales a 1 | np.ones((3))
5   |np.zeros((n))|         Crea una matriz de forma '(n)' con todos los elementos iguales a 0 utilizando la biblioteca Numpy   |   Matriz NumPy con todos los elementos iguales a 0 | np.zeros((3))
6   | np.min(array)|        Encuentra el valor mínimo en un array utilizando la biblioteca Numpy   |valor mínimo| np.min(vector_np)
7   | np.max(array)|        Encuentra el valor máximo en un array utilizando la biblioteca Numpy   |valor máximo| np.max(vector_np)
8   | np.where(CONDICIÓN SOBRE EL VECTOR)| Encuentra los índices donde se cumple una condición sobre un vector utilizando la biblioteca Numpy | Tupla de arrays con los índices donde se cumple la condición |np.where(vector_np>1)
9   |np.random.shuffle(MATRIZ)|   Permuta aleatoriamente las filas de una matriz utilizando la biblioteca Numpy  | La matriz original con sus filas reordenadas de forma aleatoria | np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
10  |array.shape[n], n=0,1 |   Accede a las dimensiones de una matriz o array utilizando el atributo 'shape' de la biblioteca Numpy   | Tamaño de la matriz o array en la dimensión especificada por 'n' | mi_matriz.shape[0]
11  |np.sum(array, axis=n), n=0,1|  Calcula la suma de los elementos de un array a lo largo del eje especificado utilizando la biblioteca Numpy | Suma de los elementos del array a lo largo del eje indicado por 'n' | np.sum(mi_matriz, axis=1)
12  |np.arange(a, b, p)|  Genera un array con valores espaciados uniformemente desde 'a' hasta 'b' (exclusivo), con un paso 'p', utilizando la biblioteca Numpy  | Array NumPy con los valores generados |np.arange(0, 10, 0.1)

# Funciones matemáticas sobre vectores

En esta sección, se aplican funciones matemáticas a un vector utilizando Python puro y NumPy. Luego, se imprime el resultado de cada función.

ACLARACIÓN: Estas funciones utilizan funciones y operaciones elementales matemáticas, sobre cada una de las posiciones del vector. Pero en general, se pueden definir funciones matemáticas que relacionan diferentes posiciones de un vector.

In [ ]:
import math

vector_py = [1, 2, 3, 4, 5]
vector_np = np.array([1, 2, 3, 4, 5])
raiz_cuadrada_py = [math.sqrt(x) for x in vector_py]
vector_cuad=[(x**2) for x in vector_np]
vector_log=[math.log(x) for x in vector_np]
raiz_cuadrada_np = np.sqrt(vector_np)
vector_npLog=np.log(vector_np)
print("Raíz cuadrada en Python puro:", raiz_cuadrada_py)
print("Raíz cuadrada en NumPy:", raiz_cuadrada_np)
print('Vector al cuadrado en Python: ',vector_cuad)
print('logaritmo de un Vector en Python: ',vector_log)
print('logaritmo de un Vector en Numpy: ',vector_npLog)

Raíz cuadrada en Python puro: [1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]
Raíz cuadrada en NumPy: [1.         1.41421356 1.73205081 2.         2.23606798]
Vector al cuadrado en Python:  [1, 4, 9, 16, 25]
logaritmo de un Vector en Python:  [0.0, 0.6931471805599453, 1.0986122886681098, 1.3862943611198906, 1.6094379124341003]
logaritmo de un Vector en Numpy:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


####  Rendimiento

En esta celda, se mide el rendimiento de operaciones en un vector utilizando Python puro y NumPy. Se imprime el tiempo de ejecución de cada operación.

In [ ]:
import time
vector_py = [i for i in range(1000000)]
vector_np = np.arange(1000000)

start_time = time.time()
[x * 2 for x in vector_py]
end_time = time.time()
print("Tiempo en Python puro:", end_time - start_time, "segundos")

start_time = time.time()
end_time = time.time()
print("Tiempo en NumPy:", end_time - start_time, "segundos")

Tiempo en Python puro: 0.05768895149230957 segundos
Tiempo en NumPy: 1.2874603271484375e-05 segundos


## Redimensionar un NumPy

A continuación se presentan dos ejemplos de redimensionamiento de un NumPy:

#### Redimensionamiento 1

En esta celda, se crea un NumPy 'array' y se utiliza la función reshape() de NumPy para redimensionarlo a una forma diferente. Luego, se imprime el nuevo array.

In [31]:
array = np.array([1, 2, 3, 4, 5, 6])
nuevo_array = array.reshape((2, 3))
print("Nuevo array redimensionado:", nuevo_array)

Nuevo array redimensionado: [[1 2 3]
 [4 5 6]]


#### Redimensionamiento 2

En esta celda, se crea un NumPy 'array' y se utiliza la función np.resize() de NumPy para redimensionarlo a una forma diferente. Luego, se imprime el nuevo array.

In [32]:
array = np.array([1, 2, 3, 4, 5, 6])
nuevo_array = np.resize(array, (3, 3))
print("Nuevo array redimensionado:", nuevo_array)

Nuevo array redimensionado: [[1 2 3]
 [4 5 6]
 [1 2 3]]


# ***EJERCICIOS PARTE 2***

**Ejercicio 1:**

Dado una matriz de datos, dividir el 70% de filas en un array_entrenamiento y el otro 30% en otro array_testeo. Esta distribución de filas de la matriz inicial, debe ser aleatoria. Mostrar las matrices al ser modificadas por el comando np.random.shuffle('matriz'). Finalmente mostrar los array_entrenamiento y array_testeo.

In [42]:
dataset = np.array([[25, 1, 7, 100, 1],
                    [30, 2, 5, 120, 0],
                    [22, 1, 6, 80, 1],
                    [28, 1, 6, 90, 0],
                    [35, 2, 4, 130, 1],
                    [32, 2, 6, 110, 1],
                    [26, 1, 8, 95, 1],
                    [24, 1, 5, 85, 0],
                    [29, 2, 7, 115, 1],
                    [31, 2, 6, 105, 0]])

# Mezclar las filas de la matriz para obtener una distribución aleatoria de los datos
np.random.shuffle(dataset)
print( dataset)

# Calcular el índice para dividir los datos en entrenamiento y prueba
total_filas = dataset.shape[0]
indice_division = int(0.7 * total_filas)
print (indice_division)

# Dividir los datos en conjunto de entrenamiento y conjunto de prueba
array_entrenamiento = dataset[:indice_division]
array_testeo = dataset[indice_division:]

# Mostrar la matriz original después de ser mezclada
print("Matriz original después de ser mezclada:\n", dataset)

# Mostrar los conjuntos de entrenamiento y prueba
print("\nConjunto de entrenamiento:\n", array_entrenamiento)
print("\nConjunto de prueba:\n", array_testeo)

[[ 35   2   4 130   1]
 [ 30   2   5 120   0]
 [ 26   1   8  95   1]
 [ 32   2   6 110   1]
 [ 25   1   7 100   1]
 [ 31   2   6 105   0]
 [ 28   1   6  90   0]
 [ 22   1   6  80   1]
 [ 29   2   7 115   1]
 [ 24   1   5  85   0]]
7
Matriz original después de ser mezclada:
 [[ 35   2   4 130   1]
 [ 30   2   5 120   0]
 [ 26   1   8  95   1]
 [ 32   2   6 110   1]
 [ 25   1   7 100   1]
 [ 31   2   6 105   0]
 [ 28   1   6  90   0]
 [ 22   1   6  80   1]
 [ 29   2   7 115   1]
 [ 24   1   5  85   0]]

Conjunto de entrenamiento:
 [[ 35   2   4 130   1]
 [ 30   2   5 120   0]
 [ 26   1   8  95   1]
 [ 32   2   6 110   1]
 [ 25   1   7 100   1]
 [ 31   2   6 105   0]
 [ 28   1   6  90   0]]

Conjunto de prueba:
 [[ 22   1   6  80   1]
 [ 29   2   7 115   1]
 [ 24   1   5  85   0]]


**Ejercicio 2:**

Dado la siguiente tabla de datos poblaciones de las Provincias de Argentina (Ejercicio 10 del Práctico 1), Realizar el siguiente analisis.

* indicar la cantidad de filas y columnas que posee la tabla de datos.
* Mostrar toda la información de la provincia con Mayor Cantidad de habitantes. AYUDA: usar la función np.max(array)
* Agregar a la tabla de datos una fila al final , indicando los totales de cada columna. Mostrar el resultado de la nueva tabla.

In [64]:

poblacionArgentina1=[
    ['PROVINCIA','CANTIDAD DE HABITANTES','CONSUMO EN MWH','SUPERFICIE EN KM^2'],
    ['Buenos Aires','17.569.053',' 16543722',' 305907'],
    ['Córdoba','3.978.984',' 10606601','164708'],
    ['Santa Fe','3.556.522',' 13078203',' 133249'],
    ['Ciudad Autónoma de Buenos Aires','3.120.612','51712507',' 201'],
    ['Mendoza','2.014.533',' 5652519',' 149069'],
    ['Tucumán','1.703.186','3208711','22.524'],
    ['Salta','1.440.672',' 2214796',' 155341'],
    ['Entre Ríos','1.426.426','3906353','78384'],
    ['Misiones','1.280.960','2845762',' 29911'],
    ['Corrientes','1.197.553','2997612',' 89123'],
    ['Chaco','1.142.963','3045380',' 99763'],
    ['Santiago del Estero','1.054.028',' 1811277',' 136934'],
    ['San Juan','818.234',' 2381940',' 88296'],
   ['Jujuy','797.955',' 1136336',' 53244'],
   ['Río Negro','762.067',' 1984782','202169'],
   ['Neuquén','726.590','1834879',' 94422'],
   ['Formosa','606.041',' 1388311','75488'],
   ['Chubut','603.120','1646029',' 224302'],
   ['San Luis','540.905',' 1780881','75347'],
   ['Catamarca','429.556',' 1337032','101486'],
   ['La Rioja','384.607','1572290',' 91494'],
   ['La Pampa','366.022','915781',' 143493'],
   ['Santa Cruz','333.473',' 1025648',' 244458'],
   ['Tierra del Fuego, Antártida e Islas del Atlántico Sur','190.641',' s/d ',' 37131']]

poblacionArgentina = np.array(poblacionArgentina1)

#print(poblacionArgentina)

# 1. Cantidad de filas y columnas
num_filas, num_columnas = poblacionArgentina.shape
print("Cantidad de filas:", num_filas)
print("Cantidad de columnas:", num_columnas)

# 2. Encontrar la provincia con mayor cantidad de habitantes

# Convertir los valores numéricos a tipos de datos adecuados (en este caso, enteros)
poblacionArgentina[1:, 1] = [int(habitantes.replace('.', '')) for habitantes in poblacionArgentina[1:, 1]]
# Extraer los valores de cantidad de habitantes como una lista
habitantes_str = [row[1] for row in poblacionArgentina[1:]]
print (habitantes_str)
# Convertir los valores de string a números en un nuevo array
poblacionArgentina = np.array(habitantes_str, dtype=int)
# Encontrar el índice de la provincia con la mayor cantidad de habitantes
indice_max_habitantes = np.argmax(poblacionArgentina[1:, 1]) + 1

# Obtener la información completa de la provincia con la mayor cantidad de habitantes
print(poblacionArgentina[indice_max_habitantes])


Cantidad de filas: 25
Cantidad de columnas: 4
['17569053', '3978984', '3556522', '3120612', '2014533', '1703186', '1440672', '1426426', '1280960', '1197553', '1142963', '1054028', '818234', '797955', '762067', '726590', '606041', '603120', '540905', '429556', '384607', '366022', '333473', '190641']


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed